apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  containers:
  - image: mongo
    name: mongo
    ports:
    - name: mongo
      containerPort: 27017
      hostPort: 27017
    volumeMounts:
    - name: mongo-persistent-storage
      mountPath: /data/db
    volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: test-pvc
